### ISSUE TITLE
pathmatch_cache crash

### ISSUE THREAD

**Issue by ThisAMJ** [p2sr/SourceAutoRecord#141]
```
#0  0x8f8e0d37 in void __gnu_cxx::new_allocator<dirent>::construct<dirent, dirent const&>(dirent*, dirent const&) () from /home/jesse/.p2-common/sar.so
#1  0x8f8e06ff in void std::allocator_traits<std::allocator<dirent> >::construct<dirent, dirent const&>(std::allocator<dirent>&, dirent*, dirent const&) () from /home/jesse/.p2-common/sar.so
#2  0x8f8e07ce in void std::vector<dirent, std::allocator<dirent> >::_M_realloc_insert<dirent const&>(__gnu_cxx::__normal_iterator<dirent*, std::vector<dirent, std::allocator<dirent> > >, dirent const&) () from /home/jesse/.p2-common/sar.so
#3  0x8f8dff77 in std::vector<dirent, std::allocator<dirent> >::push_back(dirent const&) () from /home/jesse/.p2-common/sar.so
#4  0x8f8dec35 in dc_find_or_populate(char const*) () from /home/jesse/.p2-common/sar.so
#5  0x8f8df033 in dircache_opendir(char const*) () from /home/jesse/.p2-common/sar.so
#6  0x8f8df3fb in pathmatchDetour(char const*, char**, bool, char*, unsigned int) () from /home/jesse/.p2-common/sar.so
```

**Comment by mlugg** [comment]
epic fix made it worse
